title: ShadowRooted
description: Apasionado por la ciberseguridad y el hacking ético
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
url: "https://shadowrooted.github.io"
baseurl: ""
show_github: false
