title: ShadowRooted
description: Aquí muestro mis logros, write-ups, herramientas, y quizás noticias de ciberseguridad!
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
url: "https://shadowrooted.github.io"
baseurl: ""
